export enum SocialSite {
  BANDCAMP = 'bandcamp',
  BLUESKY = 'Bluesky',
  DISCORD = 'discord',
  FACEBOOK = 'Facebook',
  INSTAGRAM = 'Instagram',
  LINKEDIN = 'LinkedIn',
  PINTEREST = 'Pinterest',
  REDDIT = 'Reddit',
  SNAPCHAT = 'Snapchat',
  SOUNDCLOUD = 'SoundCloud',
  SPOTIFY = 'Spotify',
  TIKTOK = 'TikTok',
  TWITCH = 'Twitch',
  X_TWITTER = 'X',
  YOUTUBE = 'YouTube',
  OTHER = 'Other',
}
